# Generated by Django 5.2.6 on 2025-10-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_certificaterequest_certificate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cor_id',
            field=models.FileField(blank=True, null=True, upload_to='uploads/cor_id/'),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='certificate_type',
            field=models.CharField(choices=[('good_moral', 'Good Moral Certificate'), ('enrollment', 'Certificate of Enrollment'), ('registration_form', 'Registration Form'), ('cog', 'Certificate of Grades'), ('diploma', 'Diploma')], max_length=50),
        ),
    ]
