# Generated by Django 5.2.6 on 2025-12-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_adminprofile_employee_id_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
