# Generated by Django 5.2.6 on 2025-12-12 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_actionlogs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('APPROVE', 'Approved profile'), ('REJECT', 'Rejected profile'), ('UPDATE', 'Updated profile'), ('APPOINTMENT', 'Processed appointment'), ('CERTIFICATE', 'Processed certificate request')], max_length=50)),
                ('message', models.TextField()),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='ActionLogs',
        ),
    ]
