# Generated by Django 5.2.6 on 2025-12-18 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_actionlog_delete_actionlogs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='related_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_requests', to='core.appointment'),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('APPROVE', 'Approved Profile'), ('REJECT', 'Rejected Profile'), ('UPDATE', 'Updated Profile'), ('APPOINTMENT', 'Processed Appointment'), ('CERTIFICATE', 'Processed Certificate Request')], max_length=50),
        ),
    ]
