# Generated by Django 5.2.6 on 2025-12-18 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_certificaterequest_related_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificaterequest',
            name='related_appointment',
        ),
        migrations.RemoveField(
            model_name='certificaterequest',
            name='released_at',
        ),
        migrations.RemoveField(
            model_name='certificaterequest',
            name='released_by',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appointment'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.certificaterequest'),
        ),
    ]
