# Generated by Django 5.2.6 on 2025-12-18 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_certificaterequest_related_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='core.appointment'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='core.certificaterequest'),
        ),
    ]
