# Generated by Django 5.2.6 on 2025-12-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_actionlog_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
