# Generated by Django 5.2.6 on 2025-12-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_certificaterequest_is_notified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
